<div class="grid grid-rows-2 grid-flow-col justify-center justify-items-center place-content-center bg-gray-100 gap-4">
    <div>
        <iframe 
  src="https://al-faidah.com/e/radio/RadioQuran?theme=rii&mode=card"
  scrolling="no"
  frameborder="0" 
  width="320"
  height="220"></iframe>
    </div>
    <div>
        <iframe 
  src="https://al-faidah.com/e/radio/RadioNasehatAmbon?theme=rii&mode=card"
  scrolling="no"
  frameborder="0" 
  width="320"
  height="220"></iframe>
        </div>
    <div>
        <iframe 
  src="https://al-faidah.com/e/radio/RadioIndahSiar?theme=rii&mode=card"
  scrolling="no"
  frameborder="0" 
  width="320"
  height="220"></iframe>
    </div>
    <div>
        <iframe 
  src="https://al-faidah.com/e/radio/RadioIslamMalang1?theme=rii&mode=card"
  scrolling="no"
  frameborder="0" 
  width="320"
  height="220"></iframe>
    </div>
</div>  

